export const mockEmployees = {
  list: [
    {
      id: "emp_1",
      surname: "Adeoye",
      firstName: "Adetola",
      username: "@ade_ade_41fd",
      walletAddress: "0x54...41fd",
      role: "HR Manager",
      salary: 500000,
      status: "active",
      department: "Human Resources",
    },
    {
      id: "emp_2",
      surname: "Balogun",
      firstName: "Timi",
      username: "@tim_bal_932a",
      walletAddress: "0x19b...aa34",
      role: "Graphics Designer",
      salary: 420000,
      status: "active",
      department: "Design",
    },
    {
      id: "emp_3",
      surname: "Hassan",
      firstName: "Amina",
      username: "@ami_has_782c",
      walletAddress: "0x32f...bb12",
      role: "Finance Officer",
      salary: 600000,
      status: "active",
      department: "Finance",
    },
    {
      id: "emp_4",
      surname: "Eze",
      firstName: "Chidera",
      username: "@chi_eze_621b",
      walletAddress: "0x91d...441a",
      role: "Product Manager",
      salary: 750000,
      status: "active",
      department: "Product",
    },
    {
      id: "emp_5",
      surname: "Johnson",
      firstName: "Femi",
      username: "@fem_joh_703e",
      walletAddress: "0x82f...c913",
      role: "Software Engineer",
      salary: 850000,
      status: "active",
      department: "Engineering",
    },
    {
      id: "emp_6",
      surname: "Uche",
      firstName: "Kelechi",
      username: "@kel_uch_584a",
      walletAddress: "0x66d...193b",
      role: "Operations Lead",
      salary: 700000,
      status: "active",
      department: "Operations",
    },
    {
      id: "emp_7",
      surname: "Ojo",
      firstName: "Tolu",
      username: "@tol_ojo_298d",
      walletAddress: "0x92f...77bc",
      role: "Business Analyst",
      salary: 580000,
      status: "active",
      department: "Business",
    },
    {
      id: "emp_8",
      surname: "Yusuf",
      firstName: "Mariam",
      username: "@mar_yus_613b",
      walletAddress: "0x15d...ac22",
      role: "Accountant",
      salary: 620000,
      status: "active",
      department: "Finance",
    },
    {
      id: "emp_9",
      surname: "Adebayo",
      firstName: "Ridwan",
      username: "@rid_ade_990f",
      walletAddress: "0x48b...f61d",
      role: "Backend Developer",
      salary: 800000,
      status: "active",
      department: "Engineering",
    },
  ],
}
