export const mockPayroll = {
  batches: [
    {
      id: "batch_1",
      batchName: "CSR Initiative Funding for Community Development",
      totalAmount: 3500000,
      date: "25 Oct, 2025",
      time: "7:45 AM",
      employees: 4,
      status: "Draft",
      recipients: [
        { username: "@ade_ade_41fd", fullName: "Adeoye Adetola", amount: 500000, role: "HR Manager" },
        { username: "@chi_eze_621b", fullName: "Eze Chidera", amount: 750000, role: "Product Manager" },
        { username: "@fem_joh_703e", fullName: "Johnson Femi", amount: 850000, role: "Software Engineer" },
        { username: "@tol_ojo_298d", fullName: "Ojo Tolu", amount: 580000, role: "Business Analyst" },
      ],
    },
    {
      id: "batch_2",
      batchName: "CSR Initiative Funding for Community Development",
      totalAmount: 3500000,
      date: "25 Oct, 2025",
      time: "7:45 AM",
      employees: 4,
      status: "Draft",
      recipients: [
        { username: "@ade_ade_41fd", fullName: "Adeoye Adetola", amount: 500000, role: "HR Manager" },
        { username: "@chi_eze_621b", fullName: "Eze Chidera", amount: 750000, role: "Product Manager" },
        { username: "@fem_joh_703e", fullName: "Johnson Femi", amount: 850000, role: "Software Engineer" },
        { username: "@tol_ojo_298d", fullName: "Ojo Tolu", amount: 580000, role: "Business Analyst" },
      ],
    },
    {
      id: "batch_3",
      batchName: "CSR Initiative Funding for Community Development",
      totalAmount: 3500000,
      date: "25 Oct, 2025",
      time: "7:45 AM",
      employees: 4,
      status: "Draft",
      recipients: [
        { username: "@ade_ade_41fd", fullName: "Adeoye Adetola", amount: 500000, role: "HR Manager" },
        { username: "@chi_eze_621b", fullName: "Eze Chidera", amount: 750000, role: "Product Manager" },
        { username: "@fem_joh_703e", fullName: "Johnson Femi", amount: 850000, role: "Software Engineer" },
        { username: "@tol_ojo_298d", fullName: "Ojo Tolu", amount: 580000, role: "Business Analyst" },
      ],
    },
    {
      id: "batch_4",
      batchName: "CSR Initiative Funding for Community Development",
      totalAmount: 3500000,
      date: "25 Oct, 2025",
      time: "7:45 AM",
      employees: 4,
      status: "Draft",
      recipients: [
        { username: "@ade_ade_41fd", fullName: "Adeoye Adetola", amount: 500000, role: "HR Manager" },
        { username: "@chi_eze_621b", fullName: "Eze Chidera", amount: 750000, role: "Product Manager" },
        { username: "@fem_joh_703e", fullName: "Johnson Femi", amount: 850000, role: "Software Engineer" },
        { username: "@tol_ojo_298d", fullName: "Ojo Tolu", amount: 580000, role: "Business Analyst" },
      ],
    },
    {
      id: "batch_5",
      batchName: "CSR Initiative Funding for Community Development",
      totalAmount: 3500000,
      date: "25 Oct, 2025",
      time: "7:45 AM",
      employees: 4,
      status: "Draft",
      recipients: [
        { username: "@ade_ade_41fd", fullName: "Adeoye Adetola", amount: 500000, role: "HR Manager" },
        { username: "@chi_eze_621b", fullName: "Eze Chidera", amount: 750000, role: "Product Manager" },
        { username: "@fem_joh_703e", fullName: "Johnson Femi", amount: 850000, role: "Software Engineer" },
        { username: "@tol_ojo_298d", fullName: "Ojo Tolu", amount: 580000, role: "Business Analyst" },
      ],
    },
    {
      id: "batch_6",
      batchName: "CSR Initiative Funding for Community Development",
      totalAmount: 3500000,
      date: "25 Oct, 2025",
      time: "7:45 AM",
      employees: 4,
      status: "Draft",
      recipients: [
        { username: "@ade_ade_41fd", fullName: "Adeoye Adetola", amount: 500000, role: "HR Manager" },
        { username: "@chi_eze_621b", fullName: "Eze Chidera", amount: 750000, role: "Product Manager" },
        { username: "@fem_joh_703e", fullName: "Johnson Femi", amount: 850000, role: "Software Engineer" },
        { username: "@tol_ojo_298d", fullName: "Ojo Tolu", amount: 580000, role: "Business Analyst" },
      ],
    },
  ],
  stats: {
    totalBatches: 6,
    pendingApproval: 0,
    executedThisMonth: 2,
    employeesPaid: 3,
  },
}
