export const mockProposals = {
  list: [
    {
      id: "prop_1",
      title: "CSR Initiative Batch 1",
      description: "Community development and social responsibility initiative",
      amount: 5000000,
      status: "Completed",
      timeLeft: "34 hrs 56 mins",
      votesFor: 5,
      votesAgainst: 2,
      createdAt: "2025-10-20",
      createdBy: "CEO",
    },
    {
      id: "prop_2",
      title: "Staff Welfare Increment",
      description: "Quarterly staff welfare and benefits increment",
      amount: 2500000,
      status: "In progress",
      timeLeft: "34 hrs 56 mins",
      votesFor: 3,
      votesAgainst: 2,
      createdAt: "2025-10-21",
      createdBy: "HR Manager",
    },
    {
      id: "prop_3",
      title: "Q4 Payroll Disbursement",
      description: "Fourth quarter payroll disbursement for all employees",
      amount: 8500000,
      status: "Completed",
      timeLeft: "34 hrs 56 mins",
      votesFor: 3,
      votesAgainst: 2,
      createdAt: "2025-10-22",
      createdBy: "CFO",
    },
  ],
}
