export const mockTransactions = {
  list: [
    {
      id: "txn_1",
      batchName: "CSR Initiative Funding for Community Development",
      initiatedBy: "CEO",
      totalAmount: 3500000,
      type: "Outflow",
      date: "25 Oct, 2025",
      time: "7:45 AM",
      status: "Completed",
      transactionHash: "0x7228...8q",
    },
    {
      id: "txn_2",
      batchName: "Employee Payroll Disbursement",
      initiatedBy: "HR Manager",
      totalAmount: 5820000,
      type: "Outflow",
      date: "25 Oct, 2025",
      time: "5:23 AM",
      status: "Completed",
      transactionHash: "0x1d3fa9...b",
    },
    {
      id: "txn_3",
      batchName: "Women Empowerment Skill",
      initiatedBy: "HR Manager",
      totalAmount: 2400000,
      type: "Outflow",
      date: "24 Oct, 2025",
      time: "9:23 AM",
      status: "Failed",
      transactionHash: "0x91a9ffe...e",
    },
    {
      id: "txn_4",
      batchName: "Incoming Funding: Partner Organization",
      initiatedBy: "COO",
      totalAmount: 6000000,
      type: "Inflow",
      date: "22 Oct, 2025",
      time: "11:23 AM",
      status: "Completed",
      transactionHash: "0xa4cc91e...c",
    },
    {
      id: "txn_5",
      batchName: "Investment Returns",
      initiatedBy: "CEO",
      totalAmount: 2800000,
      type: "Inflow",
      date: "21 Oct, 2025",
      time: "5:23 AM",
      status: "Completed",
      transactionHash: "0x8ae174a...a",
    },
    {
      id: "txn_6",
      batchName: "Tax Remittance (Q4 Compliance)",
      initiatedBy: "HR Manager",
      totalAmount: 950000,
      type: "Outflow",
      date: "20 Oct, 2025",
      time: "4:23 AM",
      status: "Completed",
      transactionHash: "0x83b28a1c",
    },
    {
      id: "txn_7",
      batchName: "Rural Market Development Funding",
      initiatedBy: "HR Manager",
      totalAmount: 1800000,
      type: "Outflow",
      date: "19 Oct, 2025",
      time: "5:23 AM",
      status: "Failed",
      transactionHash: "0x25c62f8...",
    },
    {
      id: "txn_8",
      batchName: "Employee Payroll Disbursement",
      initiatedBy: "HR Manager",
      totalAmount: 5820000,
      type: "Outflow",
      date: "25 Oct, 2025",
      time: "5:23 AM",
      status: "Completed",
      transactionHash: "0x1d3fa9...b",
    },
  ],
  stats: {
    totalTransactions: 158,
    outflow: 20290000,
    inflow: 8800000,
    pendingTransactions: 7,
  },
}
