export const mockUsers = {
  currentUser: {
    id: "user_1",
    walletAddress: "0x54...41fd",
    username: "@bello_dami_6fad",
    fullName: "Bello Dami",
    email: "bello@dizburza.com",
    role: "signer",
    accountType: "organization",
    createdAt: "2025-01-15",
  },
  employees: [
    {
      id: "emp_1",
      username: "@ade_ade_41fd",
      fullName: "Adeoye Adetola",
      email: "adeoye@company.com",
      jobRole: "HR Manager",
      salary: 500000,
      walletAddress: "0x54...41fd",
      department: "Human Resources",
      employeeId: "EMP001",
      status: "active",
    },
    {
      id: "emp_2",
      username: "@tim_bal_932a",
      fullName: "Balogun Timi",
      email: "timi@company.com",
      jobRole: "Graphics Designer",
      salary: 420000,
      walletAddress: "0x19b...aa34",
      department: "Design",
      employeeId: "EMP002",
      status: "active",
    },
    {
      id: "emp_3",
      username: "@ami_has_782c",
      fullName: "Hassan Amina",
      email: "amina@company.com",
      jobRole: "Finance Officer",
      salary: 600000,
      walletAddress: "0x32f...bb12",
      department: "Finance",
      employeeId: "EMP003",
      status: "active",
    },
    {
      id: "emp_4",
      username: "@chi_eze_621b",
      fullName: "Eze Chidera",
      email: "chidera@company.com",
      jobRole: "Product Manager",
      salary: 750000,
      walletAddress: "0x91d...441a",
      department: "Product",
      employeeId: "EMP004",
      status: "active",
    },
    {
      id: "emp_5",
      username: "@fem_joh_703e",
      fullName: "Johnson Femi",
      email: "femi@company.com",
      jobRole: "Software Engineer",
      salary: 850000,
      walletAddress: "0x82f...c913",
      department: "Engineering",
      employeeId: "EMP005",
      status: "active",
    },
    {
      id: "emp_6",
      username: "@kel_uch_584a",
      fullName: "Uche Kelechi",
      email: "kelechi@company.com",
      jobRole: "Operations Lead",
      salary: 700000,
      walletAddress: "0x66d...193b",
      department: "Operations",
      employeeId: "EMP006",
      status: "active",
    },
    {
      id: "emp_7",
      username: "@tol_ojo_298d",
      fullName: "Ojo Tolu",
      email: "tolu@company.com",
      jobRole: "Business Analyst",
      salary: 580000,
      walletAddress: "0x92f...77bc",
      department: "Business",
      employeeId: "EMP007",
      status: "active",
    },
    {
      id: "emp_8",
      username: "@mar_yus_613b",
      fullName: "Yusuf Mariam",
      email: "mariam@company.com",
      jobRole: "Accountant",
      salary: 620000,
      walletAddress: "0x15d...ac22",
      department: "Finance",
      employeeId: "EMP008",
      status: "active",
    },
    {
      id: "emp_9",
      username: "@rid_ade_990f",
      fullName: "Adebayo Ridwan",
      email: "ridwan@company.com",
      jobRole: "Backend Developer",
      salary: 800000,
      walletAddress: "0x48b...f61d",
      department: "Engineering",
      employeeId: "EMP009",
      status: "active",
    },
  ],
}
